# Generated by Django 3.1.4 on 2021-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.IntegerField(choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Contractor')], default=1),
            preserve_default=False,
        ),
    ]
