# Generated by Django 3.2 on 2021-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='rules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='wage_type',
            field=models.PositiveIntegerField(choices=[(0, 'Salaried'), (1, 'Per Rate')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefit',
            name='calc_mode',
            field=models.IntegerField(choices=[(0, 'Percentage'), (1, 'Fixed'), (2, 'Rulebase')], default=0),
        ),
    ]
