# Generated by Django 3.1.4 on 2021-02-27 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
