# Generated by Django 3.2 on 2021-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210524_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_position',
            field=models.ManyToManyField(through='employee.EmployeePosition', to='employee.Job'),
        ),
    ]
