# Generated by Django 3.2 on 2021-07-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeposition',
            name='employee_position_benefit',
            field=models.ManyToManyField(related_name='EmployeePositionBenefit', to='employee.Benefit'),
        ),
    ]
