# Generated by Django 3.1.4 on 2021-03-02 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeposition',
            name='position_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='income_type',
            field=models.PositiveIntegerField(choices=[(5, 'Annually'), (4, 'Quarter'), (3, 'Monthly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')], default=3),
        ),
    ]
