# Generated by Django 3.2 on 2021-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeeposition_employee_position_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_benefit',
            field=models.ManyToManyField(through='employee.EmployeeBenefit', to='employee.Benefit'),
        ),
    ]
