# Generated by Django 3.2 on 2021-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_employee_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position_benefit',
            field=models.ManyToManyField(through='employee.JobBenefit', to='employee.Benefit'),
        ),
    ]
