# Generated by Django 3.1.4 on 2021-03-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210302_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'get_latest_by': ['position_date']},
        ),
    ]
