# Generated by Django 3.1.4 on 2021-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210306_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
