# Generated by Django 3.2 on 2021-10-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20210730_1213'),
        ('employee', '0006_job_position_benefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='position_benefit',
            new_name='job_benefit',
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'unique_together': {('bank', 'account_number')},
            },
        ),
    ]
