# Generated by Django 3.1.4 on 2021-03-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210308_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
