# Generated by Django 3.2 on 2021-11-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20211031_1248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeaccount',
            unique_together=set(),
        ),
    ]
