# Generated by Django 3.1.4 on 2021-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210308_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
