# Generated by Django 3.2 on 2021-12-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20210730_1213'),
        ('employee', '0008_alter_employeeaccount_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccount',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='bank',
            field=models.ForeignKey(limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
        ),
    ]
