# Generated by Django 3.2 on 2021-12-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20211209_1949'),
        ('employee', '0010_auto_20211209_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccount',
            name='link_acc',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='link_account', to='accounting.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='bank',
            field=models.ForeignKey(limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_account', to='accounting.account'),
        ),
    ]
