# Generated by Django 3.1.4 on 2021-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='earning',
            field=models.CharField(default=0.0, max_length=25),
            preserve_default=False,
        ),
    ]
