# Generated by Django 3.1.4 on 2021-03-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20210308_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeposition',
            old_name='income_type',
            new_name='pay_period',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='income_type',
            new_name='pay_period',
        ),
    ]
