# Generated by Django 3.2 on 2021-12-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20211209_1949'),
        ('employee', '0011_auto_20211210_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='link_acc',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_account', to='accounting.account'),
        ),
    ]
