# Generated by Django 3.2 on 2021-12-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employeeaccount_link_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaccount',
            name='account_number',
        ),
    ]
