# Generated by Django 3.1.4 on 2021-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20210314_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeposition',
            name='pay_period',
            field=models.PositiveIntegerField(choices=[(6, 'Annually'), (5, 'Quarter'), (4, 'Monthly'), (3, 'Bi Weekly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')], default=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_period',
            field=models.PositiveIntegerField(choices=[(6, 'Annually'), (5, 'Quarter'), (4, 'Monthly'), (3, 'Bi Weekly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')]),
        ),
    ]
