# Generated by Django 3.2 on 2021-12-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20211210_1047'),
        ('employee', '0013_remove_employeeaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='apply_to',
            field=models.PositiveIntegerField(choices=[(0, 'Salary'), (1, 'Gross'), (2, 'Net'), (4, 'Deduction'), (3, 'Extra')]),
        ),
        migrations.AlterField(
            model_name='employeeaccount',
            name='link_acc',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='link_account', to='accounting.account'),
            preserve_default=False,
        ),
    ]
