# Generated by Django 3.1.4 on 2021-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_remove_employeeposition_pay_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeposition',
            name='pay_period',
            field=models.PositiveIntegerField(choices=[(6, 'Annually'), (5, 'Quarterly'), (4, 'Monthly'), (3, 'Bi Weekly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_period',
            field=models.PositiveIntegerField(choices=[(6, 'Annually'), (5, 'Quarterly'), (4, 'Monthly'), (3, 'Bi Weekly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')]),
        ),
    ]
