# Generated by Django 3.1.4 on 2021-02-26 18:40

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('income_type', models.PositiveIntegerField(choices=[(5, 'Annually'), (4, 'Quarter'), (3, 'Monthly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')])),
                ('currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.CharField(max_length=19)),
                ('start', models.DecimalField(decimal_places=4, max_digits=19)),
                ('end', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('excess_over', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('percent', models.DecimalField(decimal_places=4, default=1.0, max_digits=19)),
                ('addition', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.revision')),
            ],
            options={
                'unique_together': {('revision', 'line_num')},
            },
        ),
    ]
