# Generated by Django 3.1.4 on 2021-03-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tax',
            new_name='TaxContribution',
        ),
    ]
