# Generated by Django 3.1.4 on 2021-03-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.CharField(max_length=25)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Income'), (1, 'Social Security'), (2, 'Other')])),
                ('pay_by', models.PositiveIntegerField(choices=[(0, 'Employee'), (1, 'Employer')])),
                ('taken_from', models.PositiveIntegerField(choices=[(0, 'Salary'), (1, 'Gross'), (2, 'Take Home'), (3, 'Extra'), (4, 'Other')])),
                ('mandatory', models.BooleanField(default=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.revision')),
            ],
        ),
    ]
