# Generated by Django 3.2 on 2021-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcontribution',
            name='taken_from',
            field=models.PositiveIntegerField(choices=[(0, 'Salary'), (1, 'Gross'), (2, 'Net'), (4, 'Deduction'), (3, 'Extra')]),
        ),
    ]
