# Generated by Django 3.1.4 on 2021-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_auto_20210311_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='taken_from',
            field=models.PositiveIntegerField(choices=[(0, 'Salary'), (1, 'Gross'), (2, 'Net'), (3, 'Take Home'), (4, 'Extra'), (5, 'Deduction'), (6, 'Other')]),
        ),
    ]
