# Generated by Django 3.2 on 2021-12-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20211222_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcontribution',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
