# Generated by Django 3.1.4 on 2021-03-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20210311_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='income_type',
            new_name='pay_period',
        ),
    ]
