# Generated by Django 3.2 on 2021-12-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_alter_taxcontribution_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='tax_contrib',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tax.taxcontribution'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='clause',
            unique_together={('tax_contrib', 'line_num')},
        ),
        migrations.RemoveField(
            model_name='clause',
            name='revision',
        ),
    ]
