# Generated by Django 3.2 on 2021-12-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_auto_20211222_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='currency',
        ),
    ]
