# Generated by Django 3.1.4 on 2021-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_auto_20210314_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='pay_period',
            field=models.PositiveIntegerField(choices=[(6, 'Annually'), (5, 'Quarterly'), (4, 'Monthly'), (3, 'Bi Weekly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')]),
        ),
    ]
