# Generated by Django 3.2 on 2021-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_remove_revision_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='pay_period',
        ),
        migrations.AddField(
            model_name='taxcontribution',
            name='tax_period',
            field=models.PositiveIntegerField(choices=[(6, 'Annually'), (5, 'Quarterly'), (4, 'Monthly'), (3, 'Bi Weekly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')], default=1),
            preserve_default=False,
        ),
    ]
