# Generated by Django 3.2 on 2021-12-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0008_auto_20211222_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcontribution',
            name='pay_period',
            field=models.PositiveIntegerField(choices=[(6, 'Annually'), (5, 'Quarterly'), (4, 'Monthly'), (3, 'Bi Weekly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Hourly')], default=1),
            preserve_default=False,
        ),
    ]
