# Generated by Django 3.2 on 2021-12-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0009_taxcontribution_pay_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcontribution',
            name='pay_period',
        ),
    ]
