# Generated by Django 3.1.4 on 2021-03-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='total_deductions',
            new_name='deductions',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='total_deductions_currency',
            new_name='deductions_currency',
        ),
    ]
