# Generated by Django 3.2 on 2021-05-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Review'), (2, 'Closed'), (3, 'Approved'), (4, 'Paid')], default=0),
        ),
    ]
