# Generated by Django 3.1.4 on 2021-02-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20210226_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deductionplan',
            old_name='test_field',
            new_name='total_paid',
        ),
        migrations.RenameField(
            model_name='deductionplan',
            old_name='test_field_currency',
            new_name='total_paid_currency',
        ),
    ]
