# Generated by Django 3.2 on 2021-05-19 14:56

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_lineitem'),
        ('payroll', '0002_payrollemployeelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(default=payroll.models.get_default_credit_account, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
        ),
    ]
