# Generated by Django 3.2 on 2021-05-31 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20210531_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
