# Generated by Django 3.2 on 2021-05-19 15:07

from django.db import migrations
import djmoney.models.fields
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_credit_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default=payroll.models.get_default_currency, max_length=3),
        ),
    ]
