# Generated by Django 3.2 on 2021-07-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20210730_1213'),
        ('payroll', '0003_auto_20210531_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addition',
            unique_together={('payroll_employee', 'item')},
        ),
    ]
