# Generated by Django 3.2 on 2021-11-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeeaccount_unique_together'),
        ('payroll', '0004_alter_addition_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PayOptionEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_start_time', models.TimeField()),
                ('clock_end_time', models.TimeField()),
                ('break_start_time', models.TimeField()),
                ('break_end_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeposition')),
            ],
        ),
    ]
