# Generated by Django 3.1.4 on 2021-02-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20210226_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='total_deduction',
            new_name='total_deductions',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='total_deduction_currency',
            new_name='total_deductions_currency',
        ),
    ]
