# Generated by Django 3.2 on 2021-05-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_lineitem'),
        ('payroll', '0005_auto_20210519_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayrollExtra',
            new_name='Addition',
        ),
    ]
