# Generated by Django 3.2 on 2021-12-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payoption_payoptionemployee_timesheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayOption',
        ),
        migrations.DeleteModel(
            name='PayOptionEmployee',
        ),
    ]
