# Generated by Django 3.2 on 2021-12-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20211209_1335'),
        ('payroll', '0006_auto_20211209_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='flag',
            field=models.IntegerField(choices=[(0, 'Ok')], default=0),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'state': 0}, on_delete=django.db.models.deletion.CASCADE, to='employee.employeeposition'),
        ),
    ]
