# Generated by Django 3.1.4 on 2021-02-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20210226_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deductable',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='deductable',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='deductable',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='deductable',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='deductable',
            name='interest_currency',
        ),
        migrations.RemoveField(
            model_name='deductable',
            name='total_deduction',
        ),
        migrations.RemoveField(
            model_name='deductable',
            name='total_deduction_currency',
        ),
        migrations.RemoveField(
            model_name='deductionplan',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='deductionplan',
            name='total_paid_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='extra_income',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='extra_income_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='gross_income',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='gross_income_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='income_tax_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='net_income',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='net_income_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='total_deductions_currency',
        ),
    ]
