# Generated by Django 3.2 on 2021-12-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20211217_1955'),
        ('payroll', '0008_auto_20211209_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollemployee',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='flag',
        ),
        migrations.AlterField(
            model_name='creditpaymentplan',
            name='deduct_from',
            field=models.IntegerField(choices=[(0, 'Salary'), (1, 'Gross'), (2, 'Net'), (3, 'Extra'), (4, 'Deduction'), (5, 'Other')], default=2),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeposition'),
        ),
    ]
