# Generated by Django 3.1.4 on 2021-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20210226_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionplan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancel'), (1, 'Active'), (2, 'Paused'), (3, 'Skip Next Paid'), (4, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.IntegerField(choices=[(3, 'Created'), (2, 'Review'), (1, 'Posted'), (0, 'Close')], default=3),
        ),
    ]
