# Generated by Django 3.1.4 on 2021-03-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20210227_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='with_salary',
            field=models.BooleanField(default=False),
        ),
    ]
