# Generated by Django 3.2 on 2021-12-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20211220_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='payroll',
        ),
    ]
