# Generated by Django 3.2 on 2021-12-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_remove_addition_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
