# Generated by Django 3.1.4 on 2021-03-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20210306_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='gross_income',
            new_name='c_gross_income',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='gross_income_currency',
            new_name='c_gross_income_currency',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='income_tax',
            new_name='c_income_tax',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='income_tax_currency',
            new_name='c_income_tax_currency',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='net_income',
            new_name='c_net_income',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='net_income_currency',
            new_name='c_net_income_currency',
        ),
    ]
