# Generated by Django 3.2 on 2021-12-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_taxcontribution_currency'),
        ('payroll', '0012_payroll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetaxcontribution',
            name='tax',
            field=models.ForeignKey(limit_choices_to={'active': True, 'mandatory': False}, on_delete=django.db.models.deletion.CASCADE, to='tax.taxcontribution'),
        ),
    ]
