# Generated by Django 3.2 on 2021-12-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20211210_1047'),
        ('payroll', '0013_alter_employeetaxcontribution_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.transaction', unique=True),
            preserve_default=False,
        ),
    ]
