# Generated by Django 3.1.4 on 2021-03-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20210307_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollemployee',
            name='c_extra_income',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='c_extra_income_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='c_salary',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='c_salary_currency',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='c_total_deductions',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='c_total_deductions_currency',
        ),
    ]
