# Generated by Django 3.1.4 on 2021-03-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20210307_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_extra_income',
            new_name='extra_income',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_extra_income_currency',
            new_name='extra_income_currency',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_gross_income',
            new_name='gross_income',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_gross_income_currency',
            new_name='gross_income_currency',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_income_tax',
            new_name='income_tax',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_income_tax_currency',
            new_name='income_tax_currency',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_net_income',
            new_name='net_income',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_net_income_currency',
            new_name='net_income_currency',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_salary_currency',
            new_name='salary_currency',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_total_deductions',
            new_name='total_deductions',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='c_total_deductions_currency',
            new_name='total_deductions_currency',
        ),
    ]
