# Generated by Django 3.1.4 on 2021-03-08 12:31

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='fix_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.00'), default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
