# Generated by Django 3.1.4 on 2021-03-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_auto_20210308_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
