# Generated by Django 3.1.4 on 2021-03-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_auto_20210308_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='salary',
            new_name='earnings',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='salary_currency',
            new_name='earnings_currency',
        ),
    ]
