# Generated by Django 3.1.4 on 2021-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20210308_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollemployee',
            name='debts',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='extras',
        ),
        migrations.AlterField(
            model_name='payrollextra',
            name='extra',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
