# Generated by Django 3.1.4 on 2021-03-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_auto_20210311_0817'),
        ('employee', '0011_auto_20210308_1317'),
        ('payroll', '0024_employeecontribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaxCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxes', models.JSONField(editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollemployee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeposition')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.tax')),
            ],
        ),
    ]
