# Generated by Django 3.1.4 on 2021-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_employeetax_employeetaxcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetaxcollection',
            name='taxes',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
