# Generated by Django 3.1.4 on 2021-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20210311_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionplan',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='EmployeeTaxCollection',
        ),
    ]
