# Generated by Django 3.1.4 on 2021-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20210312_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductable',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
