# Generated by Django 3.2 on 2021-05-31 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210531_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalledger',
            old_name='from_account_transaction_type',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='generalledger',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='generalledger',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='generalledger',
            name='to_account_transaction_type',
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounting.account'),
            preserve_default=False,
        ),
    ]
