# Generated by Django 3.2 on 2021-07-30 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20210531_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='journal',
            name='credit_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='accounting.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='journal',
            name='debit_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debit_account', to='accounting.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_num',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ending_balance_amt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
    ]
